# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-09-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonUsage',
            fields=[
                ('User', models.AutoField(primary_key=True, serialize=False)),
                ('stupidButton', models.IntegerField()),
                ('fatButton', models.IntegerField()),
                ('dumbButton', models.IntegerField()),
            ],
        ),
    ]
